### PR TITLE
Add disable community mode command, and also add it to the nuke command

### PR DESCRIPTION
**Pull request by stop-bark**
Just added disable community mode, so u don't have to do it manually when raiding, couldn't find a way to disable it with discord.py so im just using requests.

### CODE REVIEW

**Comment by TKperson** [comment]
Thanks for contributing. I'm merge everything for now. I'll make a released version of this merge along with the other 2.3.3 usage updates

**Comment by stop-bark** [comment]
> Thanks for contributing. I'm merge everything for now. I'll make a released version of this merge along with the other 2.3.3 usage updates

alr np

**Comment by cyxl** [comment]
@stop-bark  what is your discord?

**Comment by stop-bark** [comment]
uh imagine#0403
its in my bio on my github

**Comment by stop-bark** [comment]
> 
> 
> @stop-bark what is your discord?

imagine#1714 i got disabled lol

**Pull request merged**
